#!/usr/bin/env groovy

boolean success = true

/*def sanitizeString(String str) {
    str.replaceAll(/\//,'-') //  '/ => -'
}*/

try {
    node() {
        stage('Checkout') {
            checkout([
                $class: 'GitSCM',
                branches: scm.branches,
                extensions: scm.extensions + [
                    [$class: 'CleanBeforeCheckout'],
                    [$class: 'PathRestriction', excludedRegions: '', includedRegions: '^RMQ/docker/rabbitmq/.*$']
                ],
                submoduleCfg: [],
                userRemoteConfigs: [
                    //[credentialsId: 'docker-registry-az', url: 'https://github.com/zotello/prog_N_1.git']
                    [credentialsId: 'jenkins-az-with-key', url: 'git@github.com:zotello/prog_N_1.git']
                ]
            ])

            sh 'env | sort'
        }

        dir('RMQ/docker/rabbitmq') {
            stage('Build') {
                sh 'make docker'
            }

            stage('Push') {
                sh 'make push'
                sh 'make push TAG=latest'
             //   def branchTag = sanitizeString(env.BRANCH_NAME)
             //   sh "make push TAG=${branchTag}"
            }
        } // end 'dir'

    } // end node 
} catch (e) {
    echo e.toString()
    sucess = false
    currentBuild.result = 'FAILURE'
} finally {
}
